#ifndef __KEYPAD__H_
#define __KEYPAD__H__

#include "Arduino.h"

#define KEYPAD_ADC_RESOLUTION 14

class Keypad
{
public:
    // Possible key outputs generated by the keypad.
    enum class Key : uint8_t {error, none, multiple, select, left, up, down, right};
    
    // Key press detection mode options
    enum class Decode_mode : uint8_t {closest_match, thresholds};

    /// @brief Class constructor
    /// @param analogPin        : Pin on which to read the keypad analog value
    /// @param mode             : Key press decoding methods
    ///                         :   - closest_match : nearest value within tolerance 
    ///                         :   - thresholds    : midpoint thresholds between values
    /// @param tolerance        : ADC value tolerance range
    /// @param debounce_ms      : ADC reading software debouncing value (ms)
    /// @param process_verbose  : Activate process verbose debugging outputs
    /// @param debug_stream     : Debug serial stream address
    explicit Keypad(uint8_t analogPin, 
                    Decode_mode mode = Decode_mode::closest_match,
                    uint16_t tolerance = 10,
                    uint16_t debounce_ms = 25,
                    bool process_verbose = false,
                    Stream* debug_stream = &Serial);
    ~Keypad();

    // Functions used for the keypad key checks
    void update();              // Update keypad status
    bool changed() const;       // Key pressed has changed
    Key key() const;            // Debounced key currently detected
    Key last_key() const;

    int raw() const;            // Get last raw ADC value
    Decode_mode mode() const;   // Get current mode

    // Functions to set class parameters
    void set_verbose(bool process_verbose);
    void set_tolerance(uint16_t tolerance);
    void set_debounce_ms(uint16_t debounce_ms);
    void set_decode_mode(Decode_mode mode);

    void debug_print_key();

private:

    struct Key_entry
    {
        Key key;
        uint16_t adc_value;
    };

    // Class parameter variables
    uint8_t         _pin;
    bool            _verbose;
    Stream*         _debug;
    Decode_mode     _mode;
    uint16_t        _tolerance;
    uint16_t        _debounce_ms;

    // Key variables
    int             _raw_value              = 0;
    Key             _stable_key             = Key::none;
    Key             _last_stable            = Key::none;
    Key             _candidate_key          = Key::none;
    uint32_t        _candidate_mark         = 0;

    static constexpr uint16_t adc_max_value = (1 << KEYPAD_ADC_RESOLUTION) - 1;

    static constexpr Key_entry key_lookup[] = 
    {
        {Key::right,        0},
        {Key::up,        1624},
        {Key::down,      4118},
        {Key::left,      6555},
        {Key::select,   10193},
        {Key::none,     16136}
    };

    static constexpr size_t lookup_size     = sizeof(key_lookup) / sizeof(key_lookup[0]); 

    // Thresholds table between adjacent adc center values
    uint16_t _thresholds[lookup_size - 1] = {};

    // Private helper functions
    void build_thresholds_table();

    Key decode(uint16_t raw_value) const;
    Key decode_closest_match(uint16_t raw_value) const;
    Key decode_thresholds(uint16_t raw_value) const;

    void debug_key(Key key_to_print);
};

#endif