#ifndef __keypad__H_
#define __keypad__H__

#include "Arduino.h"

#define KEYPAD_ADC_RESOLUTION 14

class keypad
{
public:
    // Possible key outputs generated by the keypad.
    enum class key_ec : uint8_t {error, none, multiple, select, left, up, down, right};
    
    // Key press detection mode options
    enum class decode_mode_ec : uint8_t {closest_match, thresholds};

    /// @brief Class constructor
    /// @param analogPin        : Pin on which to read the keypad analog value
    /// @param mode             : Key press decoding methods
    ///                         :   - closest_match : nearest value within tolerance 
    ///                         :   - thresholds    : midpoint thresholds between values
    /// @param tolerance        : ADC value tolerance range
    /// @param debounce_ms      : ADC reading software debouncing value (ms)
    /// @param process_verbose  : Activate process verbose debugging outputs
    /// @param debug_stream     : Debug serial stream address
    explicit keypad(uint8_t analogPin, 
                    decode_mode_ec mode = decode_mode_ec::closest_match,
                    uint16_t tolerance = 10,
                    uint16_t debounce_ms = 25,
                    bool process_verbose = false,
                    Stream* debug_stream = &Serial);
    ~keypad();

    // Functions used for the keypad key checks
    void update();              // Update keypad status
    bool changed() const;       // Key pressed has changed
    key_ec key() const;         // Debounced key currently detected
    key_ec last_key() const;

    int raw() const;            // Get last raw ADC value
    decode_mode_ec mode() const;   // Get current mode

    // Functions to set class parameters
    void set_verbose(bool process_verbose);
    void set_debug_stream(Stream* debug_stream);
    void set_tolerance(uint16_t tolerance);
    void set_debounce_ms(uint16_t debounce_ms);
    void set_decode_mode(decode_mode_ec mode);

    void debug_print_key();

private:

    struct key_entry_s
    {
        key_ec key;
        uint16_t adc_value;
    };

    // Class parameter variables
    uint8_t         _pin;
    bool            _verbose;
    Stream*         _debug;
    decode_mode_ec  _mode;
    uint16_t        _tolerance;
    uint16_t        _debounce_ms;

    // Key variables
    int             _raw_value              = 0;
    key_ec          _stable_key             = key_ec::none;
    key_ec          _last_stable            = key_ec::none;
    key_ec          _candidate_key          = key_ec::none;
    uint32_t        _candidate_mark         = 0;

    static constexpr uint16_t adc_max_value = (1 << KEYPAD_ADC_RESOLUTION) - 1;

    static constexpr key_entry_s key_lookup[] = 
    {
        {key_ec::right,     0},
        {key_ec::up,     1624},
        {key_ec::down,   4118},
        {key_ec::left,   6555},
        {key_ec::select,10193},
        {key_ec::none,  16136}
    };

    static constexpr size_t lookup_size     = sizeof(key_lookup) / sizeof(key_lookup[0]); 

    // Thresholds table between adjacent adc center values
    uint16_t _thresholds[lookup_size - 1] = {};

    // Private helper functions
    void build_thresholds_table();

    key_ec decode(uint16_t raw_value) const;
    key_ec decode_closest_match(uint16_t raw_value) const;
    key_ec decode_thresholds(uint16_t raw_value) const;

    void debug_key(key_ec key_to_print);
};

#endif